# Generated by Django 5.1.7 on 2025-06-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsData',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('top_key_freq', models.TextField(blank=True, null=True)),
                ('tokens', models.TextField(blank=True, null=True)),
                ('tokens_v2', models.TextField(blank=True, null=True)),
                ('entities', models.TextField(blank=True, null=True)),
                ('token_pos', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('company', models.TextField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'JobsData',
            },
        ),
    ]
