# Generated by Django 5.1.7 on 2025-06-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategoryTopKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('top_keys', models.JSONField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobsdata',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='link',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
