# Generated by Django 5.1.7 on 2025-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_job', '0002_jobcategorytopkey_jobsdata_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsdata',
            name='updated_at',
            field=models.DateField(default="2000-01-01"),
            preserve_default=False,
        ),
    ]
