# Generated by Django 5.1.7 on 2025-06-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_job', '0003_jobsdata_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategorytopkey',
            name='create_at',
        ),
    ]
