# Generated by Django 5.1.7 on 2025-05-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_keyword_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsdata',
            old_name='item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='newsdata',
            old_name='photo_link',
            new_name='photo',
        ),
    ]
